/* eslint-disable react/destructuring-assignment */
/* eslint-disable jsx-a11y/no-noninteractive-tabindex */
/* eslint-disable jsx-a11y/label-has-associated-control */
/* eslint-disable jsx-a11y/anchor-is-valid */

// import Image from "next/image";

// const Card = (props: any) => (
//   // create list of profiles containing name and image

//   // Table component name and image are passed as props
//   <div className="overflow-x-auto w-full">
//     <table className="table w-full">
//       <thead>
//         <tr>
//           <th>Name</th>
//           <th>Picture</th>
//           {/* <th></th> */}
//         </tr>
//       </thead>
//       <tbody>
//         <tr>
//           <td>
//             <div className="flex items-center space-x-3">
//               <div className="avatar">
//                 <div className="mask mask-squircle w-12 h-12">
//                   <Image
//                     src="/tailwind-css-component-profile-2@56w.png"
//                     alt="Avatar Tailwind CSS Component"
//                   />
//                 </div>
//               </div>
//               <div>
//                 <div className="font-bold">Hart Hagerty</div>
//                 <div className="text-sm opacity-50">United States</div>
//               </div>
//             </div>
//           </td>

//           <th>
//             <button className="btn btn-ghost btn-xs">details</button>
//           </th>
//         </tr>

//         <tr>
//           <th>
//             <label>
//               <input type="checkbox" className="checkbox" />
//             </label>
//           </th>
//           <td>
//             <div className="flex items-center space-x-3">
//               <div className="avatar">
//                 <div className="mask mask-squircle w-12 h-12">
//                   <Image
//                     src="/tailwind-css-component-profile-3@56w.png"
//                     alt="Avatar Tailwind CSS Component"
//                   />
//                 </div>
//               </div>
//             </div>
//           </td>

//           <th>
//             <button className="btn btn-ghost btn-xs">details</button>
//           </th>
//         </tr>

//         <tr>
//           <th>
//             <label>
//               <input type="checkbox" className="checkbox" />
//             </label>
//           </th>
//           <td>
//             <div className="flex items-center space-x-3">
//               <div className="avatar">
//                 <div className="mask mask-squircle w-12 h-12">
//                   <Image
//                     src="/tailwind-css-component-profile-4@56w.png"
//                     alt="Avatar Tailwind CSS Component"
//                   />
//                 </div>
//               </div>
//               <div>
//                 <div className="font-bold">Marjy Ferencz</div>
//                 <div className="text-sm opacity-50">Russia</div>
//               </div>
//             </div>
//           </td>

//           <th>
//             <button className="btn btn-ghost btn-xs">details</button>
//           </th>
//         </tr>

//         <tr>
//           <th>
//             <label>
//               <input type="checkbox" className="checkbox" />
//             </label>
//           </th>
//           <td>
//             <div className="flex items-center space-x-3">
//               <div className="avatar">
//                 <div className="mask mask-squircle w-12 h-12">
//                   <Image
//                     src="/tailwind-css-component-profile-5@56w.png"
//                     alt="Avatar Tailwind CSS Component"
//                   />
//                 </div>
//               </div>
//               <div>
//                 <div className="font-bold">Yancy Tear</div>
//                 <div className="text-sm opacity-50">Brazil</div>
//               </div>
//             </div>
//           </td>

//           <th>
//             <button className="btn btn-ghost btn-xs">details</button>
//           </th>
//         </tr>
//       </tbody>
//       {/* <!-- foot --> */}
//       <tfoot>
//         <tr>
//           {/* <th></th> */}
//           <th>Name</th>
//           <th>Picture</th>
//           {/* <th></th> */}
//         </tr>
//       </tfoot>
//     </table>
//   </div>
// );

// export default Card;

import Head from 'next/head';

const Card = (props: any) => (
  // create list of profiles containing name and image
  <>
    <Head>
      <title>Card</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main>
      <div className="flex flex-col">
        <div className="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
          <div className="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
            <div className="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
              <table className="min-w-full divide-y divide-gray-200">
                <thead className="bg-gray-50">
                  <tr>
                    <th
                      scope="col"
                      className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                    >
                      Name
                    </th>
                    <th
                      scope="col"
                      className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                    >
                      Picture
                    </th>
                  </tr>
                </thead>
                {/* <tbody className="bg-white divide-y divide-gray-200">
                  {props.profiles.map((profile: any) => (
                    <tr key={profile.id}>
                      <td className="px-6 py-4 whitespace-nowrap">
                        <div className="flex items-center">
                          <div className="flex-shrink-0 h-10 w-10">
                            <img
                              className="h-10 w-10 rounded-full"
                              src={profile.picture}
                              alt=""
                            />
                          </div>
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody> */}
                <tbody className="bg-white divide-y divide-gray-200">
                  {/* {db.map((profile: any) => ( */}
                  {props.profiles.map((profile: any) => (
                    <tr key={profile.id}>
                      <td className="px-6 py-4 whitespace-nowrap">
                        <div className="flex items-center">
                          <div className="ml-4">
                            <div className="text-sm font-medium text-gray-900">
                              {profile.name}
                            </div>
                          </div>
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </main>
  </>
);

export default Card;
